apps:
  pages:
    - number: 1
      items:
        - App Store
        - Safari
        - Planny
        - Anytype
        - Calendar
        - Clock
        - Parallels Desktop
        - folder: Entertainment
          pages:
            - number: 1
              items:
                - Music
                - TV
                - Podcasts
                - Photos
                - Endel
                - FreeTube
        - folder: Social
          pages:
            - number: 1
              items:
                - Discord
                - Messages
                - FaceTime
                - Signal
        - folder: Games
          pages:
            - number: 1
              items:
                - GOG Galaxy
                - Steam
                - OpenEmu
                - Baldur's Gate 3
                - Knights of the Old Republic
                - "Star Wars®: Knights of the Old Republic™ II"
                - SteamWorld Quest Hand of Gilgamech
                - The Witcher (64-bit)
                - The Witcher 2
                - Pillars of Eternity
                - PillarsOfEternityII
                - ThePillar
                - Melvor Idle
                - Old Man's Journey
                - Kensho
                - Lumencraft
                - Divinity - Original Sin 2
                - Divinity - Original Sin Enhanced Edition
                - Inscryption
                - Osmos
            - number: 2
              items:
                - Chess
        - folder: Utilities
          pages:
            - number: 1
              items:
                - DaisyDisk
                - Elgato Stream Deck
                - Elsewhen
                - FSMonitor
                - Keka
                - Codepoint
                - Contexts
                - 1Password
                - Raycast
                - Hidden Bar
        - folder: Other
          pages:
            - number: 1
              items:
                - System Settings
                - Find My
                - Maps
                - Weather
                - Home
                - Apple Configurator
                - Grapher
                - Time Machine
                - Font Book
                - Mission Control
                - QuickTime Player
                - Image Capture
                - VoiceOver Utility
                - AirPort Utility
                - Migration Assistant
                - Terminal
                - Activity Monitor
                - Console
                - Keychain Access
                - System Information
                - Automator
                - Script Editor
                - Disk Utility
                - Digital Color Meter
                - ColorSync Utility
                - Screenshot
                - Bluetooth File Exchange
                - Audio MIDI Setup
                - Dictionary
                - Voice Memos
                - Preview
                - Print Center
                - Screen Sharing
        - folder: Safari Extensions
          pages:
            - number: 1
              items:
                - 1Blocker
                - 1Password for Safari
                - Bonjourr Startpage
                - Kagi Search
                - LanguageTool
                - Noir
                - Privacy.com for Safari
                - Keepa - Price Tracker
                - Tampermonkey
        - folder: Audio
          pages:
            - number: 1
              items:
                - Audio Hijack
                - Fission
                - Loopback
                - SoundSource
        - folder: Productivity
          pages:
            - number: 1
              items:
                - Affinity Designer 2
                - Affinity Photo 2
                - Affinity Publisher 2
                - Pages
                - Numbers
                - Keynote
                - Soulver 3
                - Taio
                - ScreenFlow
                - iMovie
                - Clean Email
                - Reminders
                - Notes
                - TextEdit
                - Freeform
                - Contacts
                - Stickies
                - Shortcuts
        - folder: Reference
          pages:
            - number: 1
              items:
                - Books
                - News
                - Stocks
        - folder: Utilities
          pages:
            - number: 1
              items:
                - Calculator
                - Magnet
                - PCalc
        - folder: Developer Tools
          pages:
            - number: 1
              items:
                - Visual Studio Code
                - WebStorm
                - GoLand
                - Xcode
                - Docker
                - Alacritty
                - RapidAPI
                - Proxyman
                - Codeface
                - Power JSON Editor
                - Power Plist Editor
                - Power YAML Editor
                - CotEditor
                - Rsyncinator
                - Marked 2
                - MPS 2023.2
                - DataGrip
        - folder: Trash
          pages:
            - number: 1
              items:
                - GOG Galaxy Overlay
                - GalaxyUpdater
                - Siri
                - Mail
                - Photo Booth
widgets:
  pages: []
dock_items:
  apps:
    - /System/Applications/Launchpad.app
    - /System/Volumes/Preboot/Cryptexes/App/System/Applications/Safari.app
  others:
    - path: ~/Documents
      sort: 1
    - path: ~/Downloads
      view: 1
      sort: 2
  settings:
    autohide: true
    largesize: 128
    magnification: true
    minimize-to-application: true
    mru-spaces: false
    show-recents: false
    tilesize: 16
desktop: {}
