autoload -U +X bashcompinit && bashcompinit
autoload -Uz compinit
compinit

export PATH="$HOME/.local/bin:$PATH"

eval "$(op completion zsh)"; compdef _op op

export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

eval "$(starship init zsh)"


# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/jonathan/.lmstudio/bin"
# End of LM Studio CLI section


. "$HOME/.local/bin/env"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(/Users/jonathan/.docker/completions $fpath)
autoload -Uz compinit
compinit
# End of Docker CLI completions
